### ISSUE TITLE
Dev Kit Can't Recognize NPM which installed by fnm

### ISSUE THREAD

**Issue by ZYUN-MSFT** [OfficeDev/OfficeAddinDevKit#12]
## Describe the bug

Dev Kit Can't Recognize the NPM command which is installed by `fnm`.

## Details

On a totally new environment and install node.js with `fnm`:

![fnm status](https://github.com/user-attachments/assets/b0d2273e-14d8-4994-95a7-098f476020ce)

**Check pre-requirements failed** and **create new add-in failed**:

![pre-requirements](https://github.com/user-attachments/assets/526fe753-fd38-4d27-a38c-ff4b64928885)

![create new](https://github.com/user-attachments/assets/8b9cb0b8-afa7-49e5-b8c5-d8677b92075e)

**I guess this may related to the special method that `fnm` make the system link, or the special way VSCode read environment vars.**

## Notice

**`fnm` is an Node.js official recommend way to install node.js (from Node.js official website):**

![image](https://github.com/user-attachments/assets/33e17b3a-a2e0-4378-8691-e8e23acddafc)

**Comment by ZYUN-MSFT** [comment]
Update some investigation:
1. `fnm` MUST have to initialize the env var by `fnm` command, otherwise the `node` `npm` can't be found
2. Initial script in Pwsh's profile don't affect Windows default new process
3. Due to this design, `fnm` can live together with official system installed node.js, that means on no `fnm` command init profile's shell, the system default node.js will be used.
4. **Due to 3., this issue can be work around by manually install a system level official node.js (Already verified)**

***Due to above, I suggest not to fix this issue for now, since we can't cover every node.js version manager's every special behaviors.***

**Comment by sixareen** [comment]
I just started trying to use this Kit on a clean install of Win 11 and this was the first of many errors/problems I have encountered so far. Why mention it? Because it's actually very difficult when you're starting even to work out what "manually install a system level official node.js" actually means. Starting from scratch, you don't seem to be able to install the MS Windows build tools without either going through chocalatey (i.e. I have to use the node/npm installer and it just seems to be a different version from the one that the Kit documentation link took me to; using npm directly to install the build tools doesn't seem to be possible until you've installed node/npm. Nasty loop. But the other suggested methods of installing the Windows Build Tools seem to require that I install a version of the full Visual Studio, whereas the entire point of using this Kit is just to use VS Code! Think perhaps Microsoft should at least document the more detailed steps involved in getting all the necessary components in place.
